//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.296
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jasen.Framework.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MsgResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MsgResource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Jasen.Framework.Resources.MsgResource", typeof(MsgResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Begin transaction failed.  的本地化字符串。
        /// </summary>
        internal static string BeginTransactionFailed {
            get {
                return ResourceManager.GetString("BeginTransactionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Change database failed .  的本地化字符串。
        /// </summary>
        internal static string ChangeDatabaseFailed {
            get {
                return ResourceManager.GetString("ChangeDatabaseFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Close database failed .  的本地化字符串。
        /// </summary>
        internal static string CloseDatabaseFailed {
            get {
                return ResourceManager.GetString("CloseDatabaseFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Column name required.  的本地化字符串。
        /// </summary>
        internal static string ColumnNameRequired {
            get {
                return ResourceManager.GetString("ColumnNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CommandText(sql statement or stored procedure) missing.  的本地化字符串。
        /// </summary>
        internal static string CommandTextMissing {
            get {
                return ResourceManager.GetString("CommandTextMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Commit transaction failed .  的本地化字符串。
        /// </summary>
        internal static string CommitTransactionFailed {
            get {
                return ResourceManager.GetString("CommitTransactionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Condition missing.  的本地化字符串。
        /// </summary>
        internal static string ConditionMissing {
            get {
                return ResourceManager.GetString("ConditionMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ConnectionString missing.  的本地化字符串。
        /// </summary>
        internal static string ConnectionStringMissing {
            get {
                return ResourceManager.GetString("ConnectionStringMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Database instance not existing(is null).  的本地化字符串。
        /// </summary>
        internal static string DatabaseInstanceNotExisting {
            get {
                return ResourceManager.GetString("DatabaseInstanceNotExisting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Entity is not allowed to be null . Initialize Entity.  的本地化字符串。
        /// </summary>
        internal static string EmptyEntity {
            get {
                return ResourceManager.GetString("EmptyEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Entity must contain primary key.  的本地化字符串。
        /// </summary>
        internal static string EntityMustContainPrimaryKey {
            get {
                return ResourceManager.GetString("EntityMustContainPrimaryKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ExecuteNonQuery failed.  的本地化字符串。
        /// </summary>
        internal static string ExecuteNonQueryFailed {
            get {
                return ResourceManager.GetString("ExecuteNonQueryFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ExecuteReader failed.  的本地化字符串。
        /// </summary>
        internal static string ExecuteReaderFailed {
            get {
                return ResourceManager.GetString("ExecuteReaderFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ExecuteScalar failed.  的本地化字符串。
        /// </summary>
        internal static string ExecuteScalarFailed {
            get {
                return ResourceManager.GetString("ExecuteScalarFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Get DataSet failed.  的本地化字符串。
        /// </summary>
        internal static string GetDataSetFailed {
            get {
                return ResourceManager.GetString("GetDataSetFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Get DataTable failed .  的本地化字符串。
        /// </summary>
        internal static string GetDataTableFailed {
            get {
                return ResourceManager.GetString("GetDataTableFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The identity and primary key of entity missing.  的本地化字符串。
        /// </summary>
        internal static string IDAndPKOfEntityMissing {
            get {
                return ResourceManager.GetString("IDAndPKOfEntityMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The identity of entity missing. 的本地化字符串。
        /// </summary>
        internal static string IdentityOfEntityMissing {
            get {
                return ResourceManager.GetString("IdentityOfEntityMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Initialize gateway failed.CommandExecutor is null.  的本地化字符串。
        /// </summary>
        internal static string InitializeGatewayFailed {
            get {
                return ResourceManager.GetString("InitializeGatewayFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Initialize gateway failed .ConnectionString should not be null !  的本地化字符串。
        /// </summary>
        internal static string InitializeGatewayFailedConnectionString {
            get {
                return ResourceManager.GetString("InitializeGatewayFailedConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Initialize gateway failed .Entity should not be null !  的本地化字符串。
        /// </summary>
        internal static string InitializeGatewayFailedEntity {
            get {
                return ResourceManager.GetString("InitializeGatewayFailedEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid Arguments . No null arguments allowed.  的本地化字符串。
        /// </summary>
        internal static string InvalidArguments {
            get {
                return ResourceManager.GetString("InvalidArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid database object. 的本地化字符串。
        /// </summary>
        internal static string InvalidDatabaseObject {
            get {
                return ResourceManager.GetString("InvalidDatabaseObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Entity should have a Table attribute and TableName option is not allowed to be null .  的本地化字符串。
        /// </summary>
        internal static string InvalidEntityConfig {
            get {
                return ResourceManager.GetString("InvalidEntityConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open database failed .  的本地化字符串。
        /// </summary>
        internal static string OpenDatabaseFailed {
            get {
                return ResourceManager.GetString("OpenDatabaseFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Must provide a sequence for the identity column in oracle.  的本地化字符串。
        /// </summary>
        internal static string OracleSequenceMissing {
            get {
                return ResourceManager.GetString("OracleSequenceMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Parent entity must contain primary key.  的本地化字符串。
        /// </summary>
        internal static string ParentEntityMustContainPrimaryKey {
            get {
                return ResourceManager.GetString("ParentEntityMustContainPrimaryKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Entity must contain primary key.  的本地化字符串。
        /// </summary>
        internal static string PrimaryKeyMissing {
            get {
                return ResourceManager.GetString("PrimaryKeyMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Property type(array or non-array) must match relation type.  的本地化字符串。
        /// </summary>
        internal static string PropertyTypeMustMatchAssociationType {
            get {
                return ResourceManager.GetString("PropertyTypeMustMatchAssociationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RelationAttribute should provide a foreign key in a ManyToOne relation.  的本地化字符串。
        /// </summary>
        internal static string RelationAttributeShouldHasAForeignKey {
            get {
                return ResourceManager.GetString("RelationAttributeShouldHasAForeignKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rollback transaction failed .  的本地化字符串。
        /// </summary>
        internal static string RollbackTransactionFailed {
            get {
                return ResourceManager.GetString("RollbackTransactionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Same argument types required.  的本地化字符串。
        /// </summary>
        internal static string SameArgumentTypeRequired {
            get {
                return ResourceManager.GetString("SameArgumentTypeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Must begin a transaction before calling this method.  的本地化字符串。
        /// </summary>
        internal static string ShouldBeginTransaction {
            get {
                return ResourceManager.GetString("ShouldBeginTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sorted order required.  的本地化字符串。
        /// </summary>
        internal static string SortedOrderRequired {
            get {
                return ResourceManager.GetString("SortedOrderRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Transaction is not existing.  的本地化字符串。
        /// </summary>
        internal static string TransactionNotExisting {
            get {
                return ResourceManager.GetString("TransactionNotExisting", resourceCulture);
            }
        }
    }
}
